### ISSUE TITLE
Подскажите функции mongo или python для построения маршрута на дороге

### ISSUE THREAD

**Issue by w3prog** [w3prog/GoodTravel#10]

**Comment by zmm** [comment]
К сожалению, решение задачи построения маршрута на python/mongo без использования внешних сервисов является технически очень сложной. Как минимум в ней есть шанс упереться в два ограничения: объем хранимых необходимых данных (даже для Спб их будет очень много) и настройка алгоритма (как и где брать информацию о пробках / дорожных работах / текущей средней скорости движения по конкретным улицам; как быстро осуществлять поиск по транспортному графу). 

Поэтому, на основании собственного опыта, я рекомендую вам следующую схему:
- для построения маршрутов использовать сторонние сервисы, предоставляющие JS API (https://tech.yandex.ru/maps/doc/jsapi/2.0/ref/reference/route-docpage/) и/или REST API (https://developers.google.com/maps/documentation/directions/?hl=ru, http://wiki.openstreetmap.org/wiki/Routing/online_routers)
- построение осуществлять на сервере или клиенте, кэшируя все построенные запросы, чтобы оптимизировать скорость и ресурс бесплатного API
