### ISSUE TITLE
Создание математической модели подбора маршрута по заданным критериями.

### ISSUE THREAD

**Issue by w3prog** [w3prog/GoodTravel#12]
Нужно подобрать варианты расчет подходящий мест под определенные запросы

**Comment by zmm** [comment]
Денис, здравствуйте.

Я думаю, что ваш вопрос на самом деле является задачей оптимизации на конечном (но возможно очень большом) множестве вариантов. Количество методов решения данных задач и самих задач на данный момент довольно велико и у меня нет достаточной квалификации чтобы подсказать вам математический метод, точно подходящий к вашей задаче (что на самом деле в рамках курса и дальнейшего развития приложения не требуется).  Поэтому ниже я изложу только некие общие идеи по том, как эту задачу можно решить "дешево и сердито". 

Решение можно свести к трем шагам: 
1. составление множества решений (всех мест хотя бы как-то соответствующих критериям)
2. выделение оптимального подмножества решений (всех мест, которые максимально подходят под критерии)
3. составление из мест маршрута

Первая задача требует на самом деле не столько составления списка мест, сколько правильной формулировки самих ограничений на конкретные точки маршрута в качественном и количественном виде. Например: шекспировские места, всего не более 1000 евро трат, места только в Лондоне ....

Вторая задача требует:
- ввести меру "качества" места (целевой функционал) - численную величину. Например: стоимость_посещения_места + релевантность_к_Шекспиру
- отранжировать все места по качеству

Третья задача требует исходя из ограничений на маршрут взять N самых качественных мест и попробовать (например перебором или по методу задачи об упаковке) из них составить такой маршрут, чтобы степень его отклонения от списка маршрутных ограничений.

**Comment by zmm** [comment]
Касательно математики я уточнил у Артёма Филатова. Он мне сказал, что задача сводиться к полному перебору (NP-трудная) и может быть разделена на следующие подзадачи
- задачу линейного программирования (чтобы оценить по деньгам) (полиномиальная в среднем)
- задачу коммивояжера (чтобы построить путь) (NP-трудная)
- задачу построения планов (чтобы решить проблему времени) (NP-трудная)
