### ISSUE TITLE
 Что значит оффлайн работа? JS приложение или это мобильное приложение, если мобильное тогда под какие платформы?

### ISSUE THREAD

**Issue by w3prog** [w3prog/GoodTravel#2]

**Comment by zmm** [comment]
Оффлайн работа подразумевает работу приложения при отключенном интернете. По факту это означает, что если у вашего пользователя в процессе прохождения маршрута из музеев/галерей/исторических памятников и тд оборвется соединение, то он сможет хотя бы видеть перед собой свой дальнейший маршрут в текстовом виде (или на карте, что было бы совсем идеально).

На мой взгляд, удобнее делать мобильное приложение, но на крайний случай можно сделать и веб-приложение, которое бы адаптивно отображалось в мобильном устройстве.

В качестве платформы могу порекомендовать android как более простую в освоении, но тут нет жесткого ограничения.
