### ISSUE TITLE
Основные варианты использования приложения(use case)

### ISSUE THREAD

**Issue by w3prog** [w3prog/GoodTravel#3]

**Comment by zmm** [comment]
Сценарии использования я вижу такие (они не окончательные ):
- Планирование маршрута
  - Пользователь запускает мобильное или веб-приложение
  - Пользователь авторизуется в сервисе
  - Пользователь вводит свои интересы либо выбирает из существующих тегов
  - Пользователь вводит ограничения своей поездки (где/сколько дней/когда прилетает и улетает/ где отель/сколько денег/другие пожелания)
  - Пользователь получает визуализацию сгенерированного системой маршрута 
  - При желании пользователь вносить изменения в маршрут
  - Пользователь сохраняет маршрут (у одного пользователя может быть более одного маршрута, каждый из которых он всегда может просмотреть и отредактировать)
- Следование по маршруту
  - Пользователь запускает мобильное или веб-приложение
  - Пользователь авторизуется в сервисе
  - Пользователь выбирает маршрут 
  - В процессе прохождения маршрута, пользователь отмечает отдельные этапы как пройденные и сверяется с приложением на предмет проезда/содержания следующих этапов
